linters-settings:
  funlen:
    lines: 100
    statements: 50
  dupl:
    threshold: 160

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - ineffassign
    - dogsled
    - funlen
#    - golint
    - dupl
    - gochecknoinits
    - goconst
    - gocyclo
    - gofmt
  # don't enable:
#    - gocritic
#    - goimports
#    - gosec
#    - gosimple
#    - govet
#    - ineffassign
#    - interfacer
#    - lll
#    - misspell
#    - nakedret
#    - scopelint
#    - staticcheck
#    - structcheck
#    - stylecheck
#    - typecheck
#    - unconvert
#    - unparam
#    - unused
#    - varcheck
#    - whitespace
#   - gochecknoglobals
#   - gocognit
#   - godox
#   - maligned
#   - prealloc


# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.20.x # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"