sudo: required

dist: trusty

language: go

go:
  - 1.12.x

services:
  - docker

before_install:
  - docker build -t solar/sunrise .

script:
  - docker run solar/sunrise go test --

branches:
  only:
    - dev