// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	Dummy                bool     `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

func (m *Nothing) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

type UserReg struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReg) Reset()         { *m = UserReg{} }
func (m *UserReg) String() string { return proto.CompactTextString(m) }
func (*UserReg) ProtoMessage()    {}
func (*UserReg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *UserReg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReg.Unmarshal(m, b)
}
func (m *UserReg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReg.Marshal(b, m, deterministic)
}
func (m *UserReg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReg.Merge(m, src)
}
func (m *UserReg) XXX_Size() int {
	return xxx_messageInfo_UserReg.Size(m)
}
func (m *UserReg) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReg.DiscardUnknown(m)
}

var xxx_messageInfo_UserReg proto.InternalMessageInfo

func (m *UserReg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserReg) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserReg) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserLogin struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,json=email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLogin) Reset()         { *m = UserLogin{} }
func (m *UserLogin) String() string { return proto.CompactTextString(m) }
func (*UserLogin) ProtoMessage()    {}
func (*UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLogin.Unmarshal(m, b)
}
func (m *UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLogin.Marshal(b, m, deterministic)
}
func (m *UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLogin.Merge(m, src)
}
func (m *UserLogin) XXX_Size() int {
	return xxx_messageInfo_UserLogin.Size(m)
}
func (m *UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_UserLogin proto.InternalMessageInfo

func (m *UserLogin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Cookie struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Exp                  string   `protobuf:"bytes,3,opt,name=Exp,json=exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}
func (*Cookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *Cookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cookie.Unmarshal(m, b)
}
func (m *Cookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cookie.Marshal(b, m, deterministic)
}
func (m *Cookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookie.Merge(m, src)
}
func (m *Cookie) XXX_Size() int {
	return xxx_messageInfo_Cookie.Size(m)
}
func (m *Cookie) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookie.DiscardUnknown(m)
}

var xxx_messageInfo_Cookie proto.InternalMessageInfo

func (m *Cookie) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Cookie) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Cookie) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

type UserSession struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	UserID               uint64   `protobuf:"varint,2,opt,name=UserID,json=userID,proto3" json:"UserID,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Exp                  string   `protobuf:"bytes,4,opt,name=Exp,json=exp,proto3" json:"Exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSession) Reset()         { *m = UserSession{} }
func (m *UserSession) String() string { return proto.CompactTextString(m) }
func (*UserSession) ProtoMessage()    {}
func (*UserSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *UserSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSession.Unmarshal(m, b)
}
func (m *UserSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSession.Marshal(b, m, deterministic)
}
func (m *UserSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSession.Merge(m, src)
}
func (m *UserSession) XXX_Size() int {
	return xxx_messageInfo_UserSession.Size(m)
}
func (m *UserSession) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSession.DiscardUnknown(m)
}

var xxx_messageInfo_UserSession proto.InternalMessageInfo

func (m *UserSession) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UserSession) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserSession) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UserSession) GetExp() string {
	if m != nil {
		return m.Exp
	}
	return ""
}

func init() {
	proto.RegisterType((*Nothing)(nil), "services.Nothing")
	proto.RegisterType((*UserReg)(nil), "services.UserReg")
	proto.RegisterType((*UserLogin)(nil), "services.UserLogin")
	proto.RegisterType((*Cookie)(nil), "services.Cookie")
	proto.RegisterType((*UserSession)(nil), "services.UserSession")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0x03, 0x85, 0x52, 0xe6, 0xff, 0x0f, 0xc1, 0x15, 0x0d, 0xe1, 0xa2, 0xe9, 0xc9, 0x13,
	0x89, 0x78, 0xf0, 0xe4, 0x41, 0x81, 0x03, 0x91, 0x18, 0xb3, 0x44, 0x3d, 0x79, 0xa8, 0x30, 0x29,
	0x1b, 0x68, 0xa7, 0xe9, 0x76, 0x11, 0xfc, 0xc0, 0x7e, 0x0e, 0xb3, 0xdb, 0x2d, 0x48, 0xe0, 0xe2,
	0xf1, 0xf5, 0xcd, 0xfb, 0xed, 0xf6, 0xed, 0x40, 0x43, 0x62, 0xba, 0x12, 0x53, 0x94, 0xdd, 0x24,
	0xa5, 0x8c, 0x98, 0x57, 0x68, 0xff, 0x02, 0x6a, 0x4f, 0x94, 0xcd, 0x45, 0x1c, 0xb2, 0x16, 0x54,
	0x67, 0x2a, 0x8a, 0x36, 0xed, 0xd2, 0x65, 0xe9, 0xca, 0xe3, 0xb9, 0xf0, 0xdf, 0xa0, 0xf6, 0x22,
	0x31, 0xe5, 0x68, 0x06, 0x86, 0x51, 0x20, 0x96, 0x66, 0xa0, 0xce, 0xab, 0xa8, 0x05, 0xeb, 0x80,
	0xf7, 0x1c, 0x48, 0xf9, 0x49, 0xe9, 0xac, 0x5d, 0x36, 0x86, 0x97, 0x58, 0xad, 0x3d, 0x1d, 0x8e,
	0x83, 0x08, 0xdb, 0x4e, 0xee, 0x29, 0xab, 0xfd, 0x3b, 0xa8, 0x6b, 0x6f, 0x4c, 0xa1, 0x88, 0xff,
	0x8e, 0xf6, 0x1f, 0xc0, 0xed, 0x13, 0x2d, 0x04, 0xb2, 0x26, 0x38, 0x8f, 0xb8, 0xb1, 0x49, 0x67,
	0x81, 0x1b, 0x4d, 0x7b, 0x0d, 0x96, 0x0a, 0x6d, 0xa8, 0xba, 0xd2, 0x42, 0xcf, 0x0d, 0xd7, 0x89,
	0xbd, 0x87, 0x83, 0xeb, 0xc4, 0x7f, 0x87, 0x7f, 0xfa, 0x0a, 0x13, 0x94, 0x52, 0x50, 0xcc, 0x1a,
	0x50, 0x1e, 0x0d, 0x0c, 0xa7, 0xc2, 0xcb, 0x62, 0xc0, 0xce, 0xc1, 0xd5, 0xf6, 0x68, 0x60, 0x38,
	0x15, 0xee, 0x2a, 0xa3, 0x76, 0x78, 0xe7, 0x08, 0xbe, 0xb2, 0xc5, 0xf7, 0xbe, 0x4b, 0xd0, 0xba,
	0x57, 0xd9, 0x9c, 0x52, 0xf1, 0x15, 0x64, 0x82, 0xe2, 0x49, 0xde, 0x3a, 0xeb, 0x42, 0x8d, 0x63,
	0xa8, 0xd9, 0xec, 0xa4, 0xbb, 0x7d, 0x1a, 0x5b, 0x73, 0xa7, 0xb9, 0xfb, 0x64, 0xff, 0xb0, 0x07,
	0x75, 0x53, 0x93, 0x49, 0x9c, 0xee, 0x27, 0x8c, 0x71, 0x24, 0x73, 0x0d, 0x30, 0xa6, 0x90, 0x54,
	0x66, 0x42, 0x07, 0x7e, 0xe7, 0xd7, 0xc1, 0xc5, 0x02, 0xdc, 0xc2, 0xff, 0xfe, 0x1c, 0xa7, 0x8b,
	0xa2, 0x8f, 0xc3, 0xd0, 0xd9, 0xfe, 0xd9, 0x76, 0xf0, 0xc3, 0x35, 0x5b, 0x75, 0xf3, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xbe, 0x47, 0x62, 0xc4, 0x67, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationServiceClient interface {
	RegUser(ctx context.Context, in *UserReg, opts ...grpc.CallOption) (*Cookie, error)
	LoginUser(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*Cookie, error)
	LogoutUser(ctx context.Context, in *Cookie, opts ...grpc.CallOption) (*Nothing, error)
	CheckSession(ctx context.Context, in *Cookie, opts ...grpc.CallOption) (*UserSession, error)
}

type authorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationServiceClient(cc *grpc.ClientConn) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) RegUser(ctx context.Context, in *UserReg, opts ...grpc.CallOption) (*Cookie, error) {
	out := new(Cookie)
	err := c.cc.Invoke(ctx, "/services.AuthorizationService/RegUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) LoginUser(ctx context.Context, in *UserLogin, opts ...grpc.CallOption) (*Cookie, error) {
	out := new(Cookie)
	err := c.cc.Invoke(ctx, "/services.AuthorizationService/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) LogoutUser(ctx context.Context, in *Cookie, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/services.AuthorizationService/LogoutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) CheckSession(ctx context.Context, in *Cookie, opts ...grpc.CallOption) (*UserSession, error) {
	out := new(UserSession)
	err := c.cc.Invoke(ctx, "/services.AuthorizationService/CheckSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
type AuthorizationServiceServer interface {
	RegUser(context.Context, *UserReg) (*Cookie, error)
	LoginUser(context.Context, *UserLogin) (*Cookie, error)
	LogoutUser(context.Context, *Cookie) (*Nothing, error)
	CheckSession(context.Context, *Cookie) (*UserSession, error)
}

// UnimplementedAuthorizationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorizationServiceServer struct {
}

func (*UnimplementedAuthorizationServiceServer) RegUser(ctx context.Context, req *UserReg) (*Cookie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegUser not implemented")
}
func (*UnimplementedAuthorizationServiceServer) LoginUser(ctx context.Context, req *UserLogin) (*Cookie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedAuthorizationServiceServer) LogoutUser(ctx context.Context, req *Cookie) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogoutUser not implemented")
}
func (*UnimplementedAuthorizationServiceServer) CheckSession(ctx context.Context, req *Cookie) (*UserSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSession not implemented")
}

func RegisterAuthorizationServiceServer(s *grpc.Server, srv AuthorizationServiceServer) {
	s.RegisterService(&_AuthorizationService_serviceDesc, srv)
}

func _AuthorizationService_RegUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).RegUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AuthorizationService/RegUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).RegUser(ctx, req.(*UserReg))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogin)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AuthorizationService/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).LoginUser(ctx, req.(*UserLogin))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_LogoutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cookie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).LogoutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AuthorizationService/LogoutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).LogoutUser(ctx, req.(*Cookie))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_CheckSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cookie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).CheckSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.AuthorizationService/CheckSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).CheckSession(ctx, req.(*Cookie))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegUser",
			Handler:    _AuthorizationService_RegUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _AuthorizationService_LoginUser_Handler,
		},
		{
			MethodName: "LogoutUser",
			Handler:    _AuthorizationService_LogoutUser_Handler,
		},
		{
			MethodName: "CheckSession",
			Handler:    _AuthorizationService_CheckSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
