sudo: required

dist: trusty

language: go

go:
  - 1.13.x

services:
  - docker
  - postgresql

env:
  - DOCKER_COMPOSE_VERSION=3

install: true

before_install:
  - docker build -t solar/sunrise .

script:
  - docker build -t solar/sunrise .

branches:
  only:
    - dev
